config/routes.rb
Ledgermaker::Application.routes.draw do
  resources :users

  

  resources :ledgers do
    resources :transactions
  end

  root :to => 'static#welcome'

  

end

app/models/ledger.rb
class Ledger < ActiveRecord::Base
  attr_accessible :title, :user_id
  has_many :transactions
  belongs_to :user
  validates :user_id, presence: true
  validates :title, uniqueness: {scope: :user_id}
  

  def current_balance
    transactions.current.sum('value_in_cents') / 100.0
  end

  def subscription_for(transaction)
    transactions.where(title: transaction.title)
  end

  def update_subscription(transaction, attrs)
    subscription_for(transaction).each do |t|
      t.update_attributes(attrs)
    end
  end

  def projected_balance(through = nil)
    through ||= transactions.last.date
    transactions.through(through).sum('value_in_cents') / 100.0
  end

  def balance_by_date(range = {})
    balances = Hash.new
    transaction_dates(range).each do |date|
      balances[date] = projected_balance(date)
    end
    balances
  end

  def transaction_dates(range = {})
    range[:from] ||= transactions.first.date
    range[:to] ||= transactions.last.date
    transactions.between(range[:from], range[:to]).pluck(:date).uniq
  end
end

app/models/transaction.rb
class Transaction < ActiveRecord::Base

  attr_accessible :date, :title, :value, :ledger_id, :value_in_cents
  attr_accessor :recurrence_period, :number_of_recurrences
  attr_accessible :recurrence_period, :number_of_recurrences
  validates :date, presence: true
  belongs_to :ledger

  default_scope order('date ASC')

  # Yes, this is correct. When a company offers to "credit" your account,
  # they're talking about the transaction from their perspective, not yours.
  scope :debit, where("value_in_cents >= 0")
  scope :credit, where("value_in_cents < 0")
  

  scope :between, lambda {|from, to| where("date >= ? AND date <= ?", from, to)}
  scope :before, lambda { |target_date| where("date < ?", target_date) }
  scope :through, lambda { |target_date| where("date <= ?", target_date) }
  scope :on_or_after, lambda { |target_date| where("date >= ?", target_date) }

  def self.current
    before(Date.today)
  end

  def self.projected
    on_or_after(Date.today)
  end

  def self.create_and_recur(params)
    transaction = self.create!(params)
    transaction.save
    if transaction.recurrence_period
      transaction.recur(transaction.recurrence_period, 
                        transaction.number_of_recurrences.to_i)
    end    
  end

  def credit?
    value_in_cents < 0
  end

  def debit?
    !credit?
  end

  def value
    ((value_in_cents || 0 ) / 100.0).round(2)
  end

  def value=(amount)
    update_attributes(value_in_cents: (amount.to_f * 100).to_i)
  end
  
  def recur(period, number_of_periods)
    transaction = self
    number_of_periods.times do 
      transaction = transaction.generate_recurrence(period)
    end
  end

  def recur_biweekly(number_of_periods = 1)
    recur(:biweek, number_of_periods)
  end

  def recur_weekly(number_of_periods = 1)
    recur(:week, number_of_periods)
  end

  def recur_monthly(number_of_periods = 1)
    recur(:month, number_of_periods)
  end

  def simple_date
    date.strftime("%D")
  end

  def cancel_recurrence
    forward_transactions = Transaction.where(
      "title = ? AND date >= ?", self.title, self.date
      )
    forward_transactions.destroy_all
  end

  protected

  def generate_recurrence(period)
    Transaction.create!(
      ledger_id: ledger_id, 
      title: title, 
      value_in_cents: value_in_cents, 
      date: calculated_recurrence_date(period)
    )
  end

  def calculated_recurrence_date(period)
    case period.to_sym
    when :month
      date + 1.month
    when :week
      date + 1.week
    when :biweek
      date + 2.weeks
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :display_name, :email, :uid

  has_many :ledgers
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private

  def current_user
    User.find_or_create_by_uid(uid: "TEST", display_name: "TESTER", email: "foo@bar.com")
  end

  def ensure_current_user
    unless current_user
      redirect_to root_path
    end
  end
end

app/controllers/ledgers_controller.rb
class LedgersController < ApplicationController

  before_filter :ensure_current_user

  def index
    @ledgers = current_user.ledgers
  end

  def new
    @ledger = current_user.ledgers.new
  end

  def create
    @ledger = current_user.ledgers.create(params[:ledger])
    redirect_to ledgers_path(@ledger)
  end

  def show
    @ledger = current_user.ledgers.find(params[:id])
  end

end

app/controllers/static_controller.rb
class StaticController < ApplicationController

  def welcome

  end

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController

  before_filter :ensure_current_user
  before_filter :find_active_ledger

  def new
    @transaction = @ledger.transactions.new
  end

  def create
    @transaction = @ledger.transactions.create_and_recur(params[:transaction])
    redirect_to ledgers_path(@ledger)
  end

  def show
    @transaction = @ledger.transaction.find(params[:id])
  end

  def find_active_ledger
    @ledger = current_user.ledgers.find(params[:ledger_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ledgers_helper.rb
module LedgersHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ledgermaker</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/ledgers/index.html.erb
<ul>
  <% @ledgers.each do |ledger| %>
    <li><%= link_to ledger.title, ledger_path(ledger) %></li>
  <% end %>
</ul>

<%= link_to "New Ledger", new_ledger_path %>

app/views/ledgers/new.html.erb
<%= form_for @ledger do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.submit %>
<% end %>

app/views/ledgers/show.html.erb
<h2><%= @ledger.title %></h2>
<br>
<table>
  <tr>
    <th>Title</th>
    <th>Amount</th>
    <th>Date</th>
    <th>Balance</th>
  </tr>
  <% @ledger.transactions.each do |transaction| %>
    <tr>
      <td><%= transaction.title %></td>
      <td><%= transaction.value %></td>
      <td><%= transaction.date %></td>
      <td><%= @ledger.projected_balance(transaction.date) %></td>
    </tr>
  <% end %>
</table>

<%= link_to "Ledger Index", ledgers_path %>

app/views/transactions/new.html.erb
<%= form_for [@ledger, @transaction] do |f| %>
  <%= f.label :title %><br>
  <%= f.text_field :title %><br>
  <%= f.label :value %><br>
  <%= f.text_field :value %><br>
  <%= f.label :date %><br>
  <%= f.text_field :date %><br>
  <%= f.label :recurrence_period %><br>
  <%= f.radio_button :recurrence_period, :month %><%= f.label :recurrence_period, "Monthly", value: :month %><br>
  <%= f.radio_button :recurrence_period, :week %><%= f.label :recurrence_period, "Weekly", value: :week %><br>
  <%= f.radio_button :recurrence_period, :biweek %><%= f.label :recurrence_period, "Bi-Weekly", value: :biweek %><br>
  <%= f.radio_button :recurrence_period, :no_recurrence %><%= f.label :recurrence_period, "None", value: :no_recurrence %><br>
  <%= f.label :number_of_recurrences %><br>
  <%= f.text_field :number_of_recurrences %><br>
  <%= f.submit %>

<% end %>